name: unit tests

on:
  pull_request:

jobs:
  unit-test:
    runs-on:
      ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Nodejs 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test
